#Hugo configuration
title = "rere"
baseURL = "https:\/\/rere.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = "goodlookingbean.com"
